### ISSUE TITLE
是否有办法解决反向代理的问题

### ISSUE THREAD

**Issue by 0heartland0** [Buzz2d0/Hyuga#10]
由于一台服务器web环境较多，修改docker-compose.yml文件中的端口后跑起来域名+端口看着有点别捏，如果不改端口不与其他web环境冲突就只能用新的服务器跑起来了

测试过修改端口，然后通过nginx反向代理进行转发，环境可以正常访问，但是不管是通过http访问生成的域名还是ping生成的域名，都没有数据显示，只有加上原端口号进行访问才会显示数据，是否有方法解决这个问题？

还有个问题就是默认跑起来的docker容器时区不对，我将原有的docker-compose.yml文件修改了下，解决了时区的问题，修改后的文件如下：

````
version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: hyuga_redis
    restart: always
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    volumes:
      - "./deploy/redis:/data"
      - /etc/localtime:/etc/localtime:ro

  hyuga:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyuga
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    ports:
      - 80:8000
      - "53:53/udp"
    restart: always
    depends_on:
      - "redis"
    volumes:
      - /etc/localtime:/etc/localtime:ro
````
